### PR TITLE
Implement mirroring to double the number of training examples

### PR DESCRIPTION
**Pull request by Xavientois**
Implemented mirroring (it is turned off, so the program behaviour should be the same as before as long as it is off).

To activate it, we just need to set mirroring to True in main.py

We can activate it when we want to test it with instrumentation

### CODE REVIEW

**Comment by Xavientois** [comment]
Should I include mirroring in the minmax process? In theory, using it during training should make it unnecessary during minmax. Thoughts?

**Comment by Xavientois** [comment]
Also, I'm wondering what the best way is to keep the results separate.
I am happy with cloning the repo and running it with mirroring turned on, but if you would rather some other approach, I am open to suggestions

**Comment by jacobsteves** [comment]
Sweet, didn't think that would be so short. Nice! 👍 

> Should I include mirroring in the minmax process?

If it will be short and quick to implement, it wouldn't hurt

> I am happy with cloning the repo and running it with mirroring turned on

Sounds good to me

**Comment by Xavientois** [comment]
Actually, nvm about adding it to minmax. The minmax process doesn't actually train the network. It only tests it, so there is no way to do mirroring

**Comment by DrakeMorin** [comment]
I like how simple it is. Let's merge it.

**Pull request merged**
